add main_() to validate the called function
Signed-off-by: Samuel Zhang <simpzan@gmail.com>

diff --git a/Runfile b/Runfile
--- a/Runfile
+++ b/Runfile
@@ -16,5 +16,14 @@ node.httpserver.install() {
   npm install -g http-server
 }
 help() { echo "run, the minimalist's task runner - https://github.com/simpzan/run"; }
-.tasks() { compgen -A function | grep -v "^\."; }
-${@:-.tasks}
+
+main_() {
+  if [[ -z "$@" ]]; then
+    compgen -A function | grep -v "_$"
+  elif declare -F "$1" >/dev/null; then
+    "$@"
+  else
+    echo "Error: unknown function '$1'" >&2
+  fi
+}
+main_ $@
